name: new-projects
description: Aggregate new project checklists

inputs:
  bot-email:
    description: 'Email for git config'
    default: '41898282+github-actions[bot]@users.noreply.github.com'
  bot-name:
    description: 'Name for git config'
    default: 'GitHub Action'
  commit-message:
    description: 'Commit message'
    default: '📊 Auto-update new project report'
  branch:
    description: 'Branch to push to'
    default: 'main'
  markdown_dir:
    description: Directory for generated markdown content
    required: false
  vote_actions_release:
    description: published version of shared actions
    required: false
    default: snapshot

outputs:
  report_updated:
    description: True if changes to report were made
    value: ${{ steps.commit_push.outputs.updated }}

runs:
  using: "composite"
  steps:
    - name: Setup environment
      uses: commonhaus/vote-record-actions/actions/setup-action-environment@main
      with:
        bot-email: ${{ inputs.bot-email }}
        bot-name: ${{ inputs.bot-name }}
        vote_actions_release: ${{ inputs.vote_actions_release }}

    - name: Process new projects
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        MD_DIR:       ${{ github.workspace }}/${{ inputs.markdown_dir }}
      run: |
        node vote-record-actions/dist/newProjects.js "${MD_DIR}"
        git add -A -- "${MD_DIR}"

    - name: Commit and push changes
      id: commit_push
      uses: commonhaus/vote-record-actions/actions/commit-and-push@main
      with:
        commit-message: ${{ inputs.commit-message }}
        branch: ${{ inputs.branch }}
