name: 'Store Health Reports'
description: 'Store project health reports from repository dispatch events'

inputs:
  bot-email:
    description: 'Email for git config'
    default: '41898282+github-actions[bot]@users.noreply.github.com'
  bot-name:
    description: 'Name for git config'
    default: 'GitHub Action'
  commit-message:
    description: 'Commit message'
    default: '🩺 Auto-update health report'
  branch:
    description: 'Branch to push to'
    default: 'main'
  reports:
    description: 'JSON object containing health reports'
    required: true
  start_date:
    description: 'Start date in YYYY-MM-DD format'
    required: true
  report_directory:
    description: 'Directory to store reports'
    required: false
    default: 'reports'
  vote_actions_release:
    description: published version of shared actions
    required: false
    default: snapshot

outputs:
  report_updated:
    description: True if changes to report were made
    value: ${{ steps.commit_push.outputs.updated }}

runs:
  using: "composite"
  steps:
    - name: Setup environment
      uses: ./actions/setup-action-environment
      with:
        bot-email: ${{ inputs.bot-email }}
        bot-name: ${{ inputs.bot-name }}
        vote_actions_release: ${{ inputs.vote_actions_release }}

    - name: Process health reports
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        REPORT_DIR:   ${{ github.workspace }}/${{ inputs.report_directory }}
        REPORTS:      ${{ inputs.reports }}
        START_DATE:   ${{ inputs.start_date }}
      run: |
        node vote-record-actions/dist/healthReports.js
        git add "${{ inputs.report_directory }}"

    - name: Commit and push changes
      id: commit_push
      uses: ./actions/commit-and-push
      with:
        commit-message: ${{ inputs.commit-message }}
        branch: ${{ inputs.branch }}

